import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { Search, MapPin, Star, Tractor, CalendarDays, LayoutDashboard, PackageOpen, Users, Menu, X, ChevronRight, Clock3, CheckCircle2 } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const categories = ["All tools", "Tractors", "Harvesting", "Tillage", "Planting"];

function App() {
  const [tools, setTools] = useState([]); const [rentals, setRentals] = useState([]); const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All tools"); const [onlyAvailable, setOnlyAvailable] = useState(false); const [role, setRole] = useState("Farmer");
  const [selected, setSelected] = useState(null); const [toast, setToast] = useState(""); const [mobileNav, setMobileNav] = useState(false); const [tab, setTab] = useState("browse");
  const load = async () => { try { const [t, r] = await Promise.all([axios.get(`${API}/tools`), axios.get(`${API}/rentals`)]); setTools(t.data); setRentals(r.data); } catch { setToast("Could not connect to the rental service"); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => tools.filter(t => (category === "All tools" || t.category === category) && (!onlyAvailable || t.available) && `${t.name} ${t.category} ${t.location}`.toLowerCase().includes(query.toLowerCase())), [tools, category, onlyAvailable, query]);
  const requestRental = async (tool, duration, unit) => { try { await axios.post(`${API}/rentals`, { tool_id: tool.id, duration, unit }); setSelected(null); setToast("Rental request sent successfully"); load(); setTab("history"); } catch (e) { setToast(e.response?.data?.detail || "Unable to send request"); } };
  const approveRental = async (rentalId) => { try { await axios.patch(`${API}/rentals/${rentalId}/approve`); setToast("Rental approved — farmer can now pay"); load(); } catch (e) { setToast(e.response?.data?.detail || "Unable to approve rental"); } };
  const payRental = async (rental) => { try { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; document.body.appendChild(script); await new Promise((resolve, reject) => { script.onload = resolve; script.onerror = reject; }); const { data: order } = await axios.post(`${API}/payments/order?rental_id=${rental.id}`); const checkout = new window.Razorpay({ key: order.key_id, amount: order.amount, currency: order.currency, name: "AgriRent Pro", description: `UPI rental payment: ${rental.tool_name}`, order_id: order.id, method: { upi: true, card: true, netbanking: true, wallet: true, emi: false, paylater: false }, config: { display: { blocks: { upi_block: { name: "Pay instantly with UPI", instruments: [{ method: "upi", flows: ["collect", "intent", "qr"] }] }, other_block: { name: "Other payment options", instruments: [{ method: "card" }, { method: "netbanking" }, { method: "wallet" }] } }, sequence: ["block.upi_block", "block.other_block"], preferences: { show_default_blocks: false } } }, handler: async (response) => { await axios.post(`${API}/payments/verify`, { rental_id: rental.id, razorpay_payment_id: response.razorpay_payment_id, razorpay_order_id: response.razorpay_order_id, razorpay_signature: response.razorpay_signature }); setToast("UPI payment verified — rental confirmed"); load(); }, theme: { color: "#2d6a4f" } }); checkout.open(); } catch (e) { setToast(e.response?.data?.detail || "Unable to open Razorpay checkout"); } };
  const nav = [{id:"browse", label:"Browse tools", icon: Tractor}, {id:"history", label:"My rentals", icon: CalendarDays}];
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="brand"><div className="brand-mark"><Tractor size={22}/></div><div><strong>AgriRent</strong><span>Equipment made easy</span></div><button className="icon-btn mobile-close" data-testid="close-mobile-nav" onClick={() => setMobileNav(false)}><X size={18}/></button></div>
      <div className="side-label">Workspace</div>{nav.map(({id,label,icon:Icon}) => <button key={id} className={`nav-item ${tab===id?"active":""}`} data-testid={`nav-${id}`} onClick={() => {setTab(id); setMobileNav(false)}}><Icon size={18}/>{label}{id==="history" && rentals.length>0 && <em>{rentals.length}</em>}</button>)}
      <div className="side-label role-label">Demo role</div><div className="role-picker">{["Farmer","Tool Owner","Admin"].map(r => <button key={r} className={role===r?"selected":""} data-testid={`role-${r.toLowerCase().replace(" ","-")}`} onClick={() => setRole(r)}>{r}</button>)}</div>
      <div className="sidebar-foot"><div className="avatar">{role[0]}</div><div><b>{role} view</b><span>Demo workspace</span></div></div>
    </aside>
    <main className="main-content"><header className="topbar"><button className="icon-btn mobile-menu" data-testid="open-mobile-nav" onClick={() => setMobileNav(true)}><Menu size={20}/></button><div><span className="eyebrow">{role} workspace</span><h1>{tab === "browse" ? "Find the right tool for today’s work" : "Your rental activity"}</h1></div><div className="topbar-meta"><div className="status-dot"></div><span>All systems ready</span></div></header>
      {tab === "browse" ? <><section className="hero-strip"><div><p className="eyebrow light">FIELDWORK, SIMPLIFIED</p><h2>Good tools.<br/><i>Better harvests.</i></h2><p>Rent dependable equipment from trusted local owners, exactly when your fields need it.</p></div><div className="hero-stat"><strong>{tools.length || 4}</strong><span>tools ready<br/>to rent</span></div></section>
        <section className="toolbar"><div className="search-wrap"><Search size={18}/><input data-testid="tool-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tractors, tillers, harvesters..."/></div><div className="filter-row">{categories.map(c=><button key={c} className={`filter-pill ${category===c?"chosen":""}`} data-testid={`filter-${c.toLowerCase().replace(" ","-")}`} onClick={()=>setCategory(c)}>{c}</button>)}<button className={`availability-toggle ${onlyAvailable?"on":""}`} data-testid="available-only-toggle" onClick={()=>setOnlyAvailable(!onlyAvailable)}><span></span>Available now</button></div></section>
        <section className="section-head"><div><span className="eyebrow">RECOMMENDED FOR YOU</span><h2>Available equipment <small>{visible.length} results</small></h2></div><button className="text-btn" data-testid="view-all-tools-button" onClick={()=>{setCategory("All tools");setOnlyAvailable(false)}}>View all <ChevronRight size={16}/></button></section>
        <div className="tool-grid">{visible.map(tool=><article className="tool-card" key={tool.id} data-testid={`tool-card-${tool.id}`}><div className="tool-image"><img src={tool.image_url} alt={tool.name}/><span className={tool.available?"availability available":"availability"}>{tool.available?<><span/>Available</>:"Booked"}</span><button className="quick-view" data-testid={`tool-details-${tool.id}`} onClick={()=>setSelected(tool)}>View details</button></div><div className="tool-info"><div className="tool-top"><span className="category-tag">{tool.category}</span><span className="rating"><Star size={13} fill="currentColor"/>{tool.rating}</span></div><h3>{tool.name}</h3><p className="location"><MapPin size={14}/>{tool.location}</p><div className="tool-bottom"><div className="price"><strong>₹{tool.daily_rate.toLocaleString()}</strong><span>/ day · ₹{tool.hourly_rate}/hr</span></div><button className="rent-btn" data-testid={`rent-tool-${tool.id}`} disabled={!tool.available} onClick={()=>setSelected(tool)}>Rent tool <ChevronRight size={16}/></button></div></div></article>)}</div>
      </> : <section className="history-section"><div className="history-summary"><div><span className="eyebrow">RENTAL HISTORY</span><h2>Keep your season moving.</h2><p>Requests and active rentals from this demo workspace.</p></div><div className="summary-number"><strong>{rentals.length}</strong><span>requests</span></div></div>{rentals.length===0?<div className="empty-state"><PackageOpen size={34}/><h3>No rentals yet</h3><p>Browse available equipment and your requests will appear here.</p><button className="rent-btn" data-testid="empty-browse-button" onClick={()=>setTab("browse")}>Browse tools <ChevronRight size={16}/></button></div>:<div className="rental-list">{rentals.map(r=><div className="rental-row" key={r.id} data-testid={`rental-row-${r.id}`}><div className="rental-icon"><Tractor size={20}/></div><div className="rental-main"><b>{r.tool_name}</b><span>{r.duration} {r.unit}{r.duration>1?"s":""} · Requested just now</span></div><strong>₹{r.total.toLocaleString()}</strong><span className="request-status"><Clock3 size={14}/>{r.status}</span>{(role==="Admin" || role==="Tool Owner") && r.status==="Requested" && <button className="approve-btn" data-testid={`approve-rental-${r.id}`} onClick={()=>approveRental(r.id)}>Approve</button>}{role==="Farmer" && r.status==="Approved" && r.payment_status!=="paid" && <button className="pay-btn" data-testid={`pay-rental-${r.id}`} onClick={()=>payRental(r)}>Pay via UPI</button>}</div>)}</div>}</section>}
      {toast && <div className="toast" data-testid="toast-message"><CheckCircle2 size={17}/>{toast}<button data-testid="dismiss-toast" onClick={()=>setToast("")}><X size={15}/></button></div>}
    </main>{selected && <RentalModal tool={selected} onClose={()=>setSelected(null)} onSubmit={requestRental}/>}</div>;
}

function RentalModal({tool,onClose,onSubmit}) { const [duration,setDuration]=useState(1); const [unit,setUnit]=useState("day"); const total=duration*(unit==="day"?tool.daily_rate:tool.hourly_rate); return <div className="modal-backdrop" data-testid="rental-modal"><div className="modal"><button className="modal-close icon-btn" data-testid="close-rental-modal" onClick={onClose}><X size={18}/></button><span className="eyebrow">RENTAL REQUEST</span><h2>{tool.name}</h2><p className="modal-location"><MapPin size={14}/>{tool.location} · {tool.owner}</p><div className="modal-rule"/><div className="unit-tabs"><button className={unit==="day"?"selected":""} data-testid="unit-day" onClick={()=>setUnit("day")}>Per day <span>₹{tool.daily_rate.toLocaleString()}</span></button><button className={unit==="hour"?"selected":""} data-testid="unit-hour" onClick={()=>setUnit("hour")}>Per hour <span>₹{tool.hourly_rate}</span></button></div><label className="duration-label">How long do you need it?<div className="stepper"><button data-testid="decrease-duration" onClick={()=>setDuration(Math.max(1,duration-1))}>−</button><strong data-testid="duration-value">{duration}</strong><button data-testid="increase-duration" onClick={()=>setDuration(duration+1)}>+</button></div></label><div className="total-line"><span>Estimated total</span><strong>₹{total.toLocaleString()}</strong></div><button className="confirm-btn" data-testid="confirm-rental-button" onClick={()=>onSubmit(tool,duration,unit)}>Send rental request <ChevronRight size={17}/></button><p className="modal-note">The owner will confirm availability shortly.</p></div></div> }
export default App;
