import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { Search, MapPin, Star, Tractor, CalendarDays, LayoutDashboard, PackageOpen, Users, Menu, X, ChevronRight, Clock3, CheckCircle2, Wallet, Save, Receipt, IndianRupee } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const categories = ["All tools", "Tractors", "Harvesting", "Tillage", "Planting"];

function App() {
  const [tools, setTools] = useState([]); const [rentals, setRentals] = useState([]); const [payments, setPayments] = useState([]); const [methods, setMethods] = useState(null); const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All tools"); const [onlyAvailable, setOnlyAvailable] = useState(false); const [role, setRole] = useState("Farmer");
  const [selected, setSelected] = useState(null); const [toast, setToast] = useState(""); const [mobileNav, setMobileNav] = useState(false); const [tab, setTab] = useState("browse"); const [paidReceipt, setPaidReceipt] = useState(null);
  const [upiId, setUpiId] = useState(() => localStorage.getItem("agrirent_upi_id") || ""); const [upiDraft, setUpiDraft] = useState(() => localStorage.getItem("agrirent_upi_id") || "");
  const saveUpiId = () => { const v = (upiDraft || "").trim(); if (v && !/^[\w.\-]{2,256}@[a-zA-Z]{2,64}$/.test(v)) { setToast("Enter a valid UPI ID like name@bank"); return; } localStorage.setItem("agrirent_upi_id", v); setUpiId(v); setToast(v ? `UPI ID saved — ${v} will auto-fill at checkout` : "UPI ID cleared"); };
  const load = async () => { try { const [t, r, p, m] = await Promise.all([axios.get(`${API}/tools`), axios.get(`${API}/rentals`), axios.get(`${API}/payments/history`), axios.get(`${API}/payments/methods`).catch(()=>({data:null}))]); setTools(t.data); setRentals(r.data); setPayments(p.data); setMethods(m.data); } catch { setToast("Could not connect to the rental service"); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => tools.filter(t => (category === "All tools" || t.category === category) && (!onlyAvailable || t.available) && `${t.name} ${t.category} ${t.location}`.toLowerCase().includes(query.toLowerCase())), [tools, category, onlyAvailable, query]);
  const requestRental = async (tool, duration, unit) => { try { await axios.post(`${API}/rentals`, { tool_id: tool.id, duration, unit }); setSelected(null); setToast("Rental request sent successfully"); load(); setTab("history"); } catch (e) { setToast(e.response?.data?.detail || "Unable to send request"); } };
  const approveRental = async (rentalId) => { try { await axios.patch(`${API}/rentals/${rentalId}/approve`); setToast("Rental approved — farmer can now pay"); load(); } catch (e) { setToast(e.response?.data?.detail || "Unable to approve rental"); } };
  const payRental = async (rental) => { try { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; document.body.appendChild(script); await new Promise((resolve, reject) => { script.onload = resolve; script.onerror = () => reject(new Error("Could not load Razorpay Checkout — check your internet connection")); }); let order; try { order = (await axios.post(`${API}/payments/order?rental_id=${rental.id}`)).data; } catch (e) { const msg = e.response?.data?.detail || "Could not create payment order"; setToast(msg); return; } const savedVpa = (upiId || "").trim(); const options = { key: order.key_id, amount: order.amount, currency: order.currency, name: "AgriRent Pro", description: `Rental payment · ${rental.tool_name}`, order_id: order.id, method: { upi: true, card: true, netbanking: true, wallet: true }, prefill: { name: rental.renter_name || "Farmer", email: "farmer@agrirent.demo", contact: "9999999999", ...(savedVpa ? { vpa: savedVpa, method: "upi" } : {}) }, notes: { rental_id: rental.id, tool: rental.tool_name }, theme: { color: "#2d6a4f" }, modal: { confirm_close: true, ondismiss: async () => { try { await axios.post(`${API}/payments/failed`, { rental_id: rental.id, razorpay_order_id: order.id, reason: "user_cancelled" }); } catch {} setToast("Payment cancelled — you can retry any time"); load(); } }, handler: async (response) => { try { const { data } = await axios.post(`${API}/payments/verify`, { rental_id: rental.id, razorpay_payment_id: response.razorpay_payment_id, razorpay_order_id: response.razorpay_order_id, razorpay_signature: response.razorpay_signature }); setPaidReceipt({ rental, payment_id: response.razorpay_payment_id, order_id: response.razorpay_order_id, method: data.payment_method }); setToast("Payment verified — rental confirmed"); load(); } catch (e) { setToast(e.response?.data?.detail || "Payment verification failed — please retry"); load(); } } }; const checkout = new window.Razorpay(options); checkout.on("payment.failed", async (resp) => { const err = resp?.error || {}; try { await axios.post(`${API}/payments/failed`, { rental_id: rental.id, razorpay_order_id: err.metadata?.order_id || order.id, razorpay_payment_id: err.metadata?.payment_id, code: err.code, description: err.description, reason: err.reason }); } catch {} setToast(err.description || "Payment failed — please retry"); load(); }); checkout.open(); } catch (e) { setToast(e.message || e.response?.data?.detail || "Unable to open Razorpay checkout"); } };
  const nav = [{id:"browse", label:"Browse tools", icon: Tractor}, {id:"history", label:"My rentals", icon: CalendarDays}, ...((role==="Admin"||role==="Tool Owner") ? [{id:"payments", label:"Payment history", icon: Receipt}] : [])];
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="brand"><div className="brand-mark"><Tractor size={22}/></div><div><strong>AgriRent</strong><span>Equipment made easy</span></div><button className="icon-btn mobile-close" data-testid="close-mobile-nav" onClick={() => setMobileNav(false)}><X size={18}/></button></div>
      <div className="side-label">Workspace</div>{nav.map(({id,label,icon:Icon}) => <button key={id} className={`nav-item ${tab===id?"active":""}`} data-testid={`nav-${id}`} onClick={() => {setTab(id); setMobileNav(false)}}><Icon size={18}/>{label}{id==="history" && rentals.length>0 && <em>{rentals.length}</em>}</button>)}
      <div className="side-label role-label">Demo role</div><div className="role-picker">{["Farmer","Tool Owner","Admin"].map(r => <button key={r} className={role===r?"selected":""} data-testid={`role-${r.toLowerCase().replace(" ","-")}`} onClick={() => setRole(r)}>{r}</button>)}</div>
      {role === "Farmer" && <div className="upi-profile" data-testid="upi-profile-section"><div className="side-label"><Wallet size={13} style={{marginRight:6,verticalAlign:"-2px"}}/>Saved UPI ID</div><div className="upi-input-row"><input data-testid="upi-id-input" value={upiDraft} onChange={e=>setUpiDraft(e.target.value)} placeholder="name@bank" spellCheck={false} autoComplete="off"/><button className="upi-save-btn" data-testid="save-upi-id" onClick={saveUpiId} title="Save UPI ID"><Save size={14}/></button></div>{upiId ? <span className="upi-hint saved" data-testid="upi-saved-hint">Auto-fills at UPI checkout</span> : <span className="upi-hint" data-testid="upi-empty-hint">Save once to skip typing at checkout</span>}</div>}
      <div className="sidebar-foot"><div className="avatar">{role[0]}</div><div><b>{role} view</b><span>Demo workspace</span></div></div>
    </aside>
    <main className="main-content"><header className="topbar"><button className="icon-btn mobile-menu" data-testid="open-mobile-nav" onClick={() => setMobileNav(true)}><Menu size={20}/></button><div><span className="eyebrow">{role} workspace</span><h1>{tab === "browse" ? "Find the right tool for today’s work" : tab === "payments" ? "Payment history" : "Your rental activity"}</h1></div><div className="topbar-meta"><div className="status-dot"></div><span>All systems ready</span></div></header>
      {tab === "payments" ? <section className="payments-section" data-testid="payments-section"><div className="history-summary alt"><div><span className="eyebrow">RAZORPAY LEDGER</span><h2>Payment history</h2><p>All successful and failed payment attempts recorded by Razorpay.</p></div><div className="summary-number"><strong>₹{payments.filter(p=>p.payment_status==="paid").reduce((s,p)=>s+(p.amount||0),0).toLocaleString()}</strong><span>collected · {payments.length} entries</span></div></div>{payments.length===0?<div className="empty-state" data-testid="payments-empty"><Receipt size={34}/><h3>No payments yet</h3><p>Once a farmer completes UPI checkout, the entry will appear here.</p></div>:<div className="payments-table" data-testid="payments-table"><div className="pt-head"><span>Tool</span><span>Renter</span><span>Amount</span><span>Payment ID</span><span>When</span><span>Status</span></div>{payments.map(p=><div className="pt-row" key={p.razorpay_payment_id} data-testid={`payment-row-${p.razorpay_payment_id}`}><span className="pt-tool"><Tractor size={14}/>{p.tool_name||"—"}</span><span>{p.renter_name||"—"}</span><span className="pt-amount"><IndianRupee size={12}/>{Number(p.amount||0).toLocaleString()}</span><span className="pt-id" title={p.razorpay_payment_id}>{p.razorpay_payment_id}</span><span>{p.paid_at ? new Date(p.paid_at).toLocaleString() : (p.failed_at ? new Date(p.failed_at).toLocaleString() : "—")}</span><span className={`pt-status ${p.payment_status}`}>{p.payment_status}</span></div>)}</div>}</section> : tab === "browse" ? <><section className="hero-strip"><div><p className="eyebrow light">FIELDWORK, SIMPLIFIED</p><h2>Good tools.<br/><i>Better harvests.</i></h2><p>Rent dependable equipment from trusted local owners, exactly when your fields need it.</p></div><div className="hero-stat"><strong>{tools.length || 4}</strong><span>tools ready<br/>to rent</span></div></section>
        <section className="toolbar"><div className="search-wrap"><Search size={18}/><input data-testid="tool-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tractors, tillers, harvesters..."/></div><div className="filter-row">{categories.map(c=><button key={c} className={`filter-pill ${category===c?"chosen":""}`} data-testid={`filter-${c.toLowerCase().replace(" ","-")}`} onClick={()=>setCategory(c)}>{c}</button>)}<button className={`availability-toggle ${onlyAvailable?"on":""}`} data-testid="available-only-toggle" onClick={()=>setOnlyAvailable(!onlyAvailable)}><span></span>Available now</button></div></section>
        <section className="section-head"><div><span className="eyebrow">RECOMMENDED FOR YOU</span><h2>Available equipment <small>{visible.length} results</small></h2></div><button className="text-btn" data-testid="view-all-tools-button" onClick={()=>{setCategory("All tools");setOnlyAvailable(false)}}>View all <ChevronRight size={16}/></button></section>
        <div className="tool-grid">{visible.map(tool=><article className="tool-card" key={tool.id} data-testid={`tool-card-${tool.id}`}><div className="tool-image"><img src={tool.image_url} alt={tool.name}/><span className={tool.available?"availability available":"availability"}>{tool.available?<><span/>Available</>:"Booked"}</span><button className="quick-view" data-testid={`tool-details-${tool.id}`} onClick={()=>setSelected(tool)}>View details</button></div><div className="tool-info"><div className="tool-top"><span className="category-tag">{tool.category}</span><span className="rating"><Star size={13} fill="currentColor"/>{tool.rating}</span></div><h3>{tool.name}</h3><p className="location"><MapPin size={14}/>{tool.location}</p><div className="tool-bottom"><div className="price"><strong>₹{tool.daily_rate.toLocaleString()}</strong><span>/ day · ₹{tool.hourly_rate}/hr</span></div><button className="rent-btn" data-testid={`rent-tool-${tool.id}`} disabled={!tool.available} onClick={()=>setSelected(tool)}>Rent tool <ChevronRight size={16}/></button></div></div></article>)}</div>
      </> : <section className="history-section">{methods && !methods.upi_collect && role==="Farmer" && <div className="upi-warn" data-testid="upi-disabled-banner"><b>UPI is disabled on your Razorpay test account.</b><span>Open Razorpay Dashboard → Account & Settings → Payment Methods → enable <em>UPI</em>. Once enabled, refresh this page and UPI will appear in checkout alongside Cards, Netbanking and Wallet.</span></div>}<div className="history-summary"><div><span className="eyebrow">RENTAL HISTORY</span><h2>Keep your season moving.</h2><p>Requests and active rentals from this demo workspace.</p></div><div className="summary-number"><strong>{rentals.length}</strong><span>requests</span></div></div>{rentals.length===0?<div className="empty-state"><PackageOpen size={34}/><h3>No rentals yet</h3><p>Browse available equipment and your requests will appear here.</p><button className="rent-btn" data-testid="empty-browse-button" onClick={()=>setTab("browse")}>Browse tools <ChevronRight size={16}/></button></div>:<div className="rental-list">{rentals.map(r=><div className="rental-row" key={r.id} data-testid={`rental-row-${r.id}`}><div className="rental-icon"><Tractor size={20}/></div><div className="rental-main"><b>{r.tool_name}</b><span>{r.duration} {r.unit}{r.duration>1?"s":""} · Requested just now</span></div><strong>₹{r.total.toLocaleString()}</strong><span className="request-status"><Clock3 size={14}/>{r.status}</span>{(role==="Admin" || role==="Tool Owner") && r.status==="Requested" && <button className="approve-btn" data-testid={`approve-rental-${r.id}`} onClick={()=>approveRental(r.id)}>Approve</button>}{role==="Farmer" && r.status==="Approved" && r.payment_status!=="paid" && (r.payment_status==="PAYMENT_PENDING" || r.payment_status==="failed" ? <button className="pay-btn retry" data-testid={`retry-rental-${r.id}`} onClick={()=>payRental(r)}>Retry Payment</button> : <button className="pay-btn" data-testid={`pay-rental-${r.id}`} onClick={()=>payRental(r)}>Pay via UPI</button>)}{r.payment_status && r.payment_status!=="unpaid" && r.payment_status!=="created" && <span className={`pay-pill ${String(r.payment_status).toLowerCase()}`} data-testid={`pay-pill-${r.id}`}>{String(r.payment_status).replace("_"," ").toUpperCase()}</span>}</div>)}</div>}</section>}
      {toast && <div className="toast" data-testid="toast-message"><CheckCircle2 size={17}/>{toast}<button data-testid="dismiss-toast" onClick={()=>setToast("")}><X size={15}/></button></div>}
    </main>{selected && <RentalModal tool={selected} onClose={()=>setSelected(null)} onSubmit={requestRental}/>}{paidReceipt && <div className="modal-backdrop" data-testid="paid-receipt-modal"><div className="modal receipt-modal"><button className="modal-close icon-btn" data-testid="close-paid-receipt" onClick={()=>setPaidReceipt(null)}><X size={18}/></button><div className="receipt-tick"><CheckCircle2 size={44}/></div><span className="eyebrow">PAYMENT SUCCESSFUL</span><h2>Rental confirmed</h2><p className="modal-location">{paidReceipt.rental.tool_name} · {paidReceipt.rental.duration} {paidReceipt.rental.unit}{paidReceipt.rental.duration>1?"s":""}</p><div className="modal-rule"/><div className="receipt-row"><span>Amount paid</span><strong>₹{paidReceipt.rental.total.toLocaleString()}</strong></div><div className="receipt-row"><span>Payment method</span><strong>{(paidReceipt.method || "UPI").toUpperCase()}</strong></div><div className="receipt-row"><span>Payment ID</span><code>{paidReceipt.payment_id}</code></div><div className="receipt-row"><span>Order ID</span><code>{paidReceipt.order_id}</code></div><button className="confirm-btn" data-testid="close-receipt-cta" onClick={()=>setPaidReceipt(null)}>Done <ChevronRight size={17}/></button></div></div>}</div>;
}

function RentalModal({tool,onClose,onSubmit}) { const [duration,setDuration]=useState(1); const [unit,setUnit]=useState("day"); const total=duration*(unit==="day"?tool.daily_rate:tool.hourly_rate); return <div className="modal-backdrop" data-testid="rental-modal"><div className="modal"><button className="modal-close icon-btn" data-testid="close-rental-modal" onClick={onClose}><X size={18}/></button><span className="eyebrow">RENTAL REQUEST</span><h2>{tool.name}</h2><p className="modal-location"><MapPin size={14}/>{tool.location} · {tool.owner}</p><div className="modal-rule"/><div className="unit-tabs"><button className={unit==="day"?"selected":""} data-testid="unit-day" onClick={()=>setUnit("day")}>Per day <span>₹{tool.daily_rate.toLocaleString()}</span></button><button className={unit==="hour"?"selected":""} data-testid="unit-hour" onClick={()=>setUnit("hour")}>Per hour <span>₹{tool.hourly_rate}</span></button></div><label className="duration-label">How long do you need it?<div className="stepper"><button data-testid="decrease-duration" onClick={()=>setDuration(Math.max(1,duration-1))}>−</button><strong data-testid="duration-value">{duration}</strong><button data-testid="increase-duration" onClick={()=>setDuration(duration+1)}>+</button></div></label><div className="total-line"><span>Estimated total</span><strong>₹{total.toLocaleString()}</strong></div><button className="confirm-btn" data-testid="confirm-rental-button" onClick={()=>onSubmit(tool,duration,unit)}>Send rental request <ChevronRight size={17}/></button><p className="modal-note">The owner will confirm availability shortly.</p></div></div> }
export default App;
